#!/bin/sh

# 環境変数から Amplify 設定ファイルを生成
if [ -n "$APPSYNC_ENDPOINT" ] && [ -n "$APPSYNC_API_KEY" ]; then
  echo "Generating Amplify config from environment variables..."
  cat > src/amplifyconfiguration.json << EOF
{
  "aws_project_region": "ap-northeast-1",
  "aws_appsync_graphqlEndpoint": "${APPSYNC_ENDPOINT}",
  "aws_appsync_region": "ap-northeast-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "${APPSYNC_API_KEY}"
}
EOF

  cat > src/aws-exports.js << EOF
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "${APPSYNC_ENDPOINT}",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "${APPSYNC_API_KEY}"
};


export default awsmobile;
EOF
fi

yarn run build

# オプションで port 変更ができない & 環境変数は使えないのでデフォルトポートを上書きする
sed 's|4321|3000|' -i dist/server/entry.mjs

# esbuild で bundle し、node_modules を不要にする
yarn bundle

mkdir -p .amplify-hosting/compute

mv dist/client .amplify-hosting/static
mv dist/server .amplify-hosting/compute/default

cp deploy-manifest.json .amplify-hosting/deploy-manifest.json

# external module である sharp は node_modules に含める必要がある
if [ -d node_modules/sharp ]; then
  rm -rf .amplify-hosting/compute/default/node_modules
  mkdir -p .amplify-hosting/compute/default/node_modules
  cp -r node_modules/sharp .amplify-hosting/compute/default/node_modules/
fi
